# Generated by Django 2.1.9 on 2020-01-23 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('snappfood', '0002_auto_20200123_1230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asghar', to='snappfood.Shop'),
        ),
    ]
