# Generated by Django 2.1.9 on 2020-01-23 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snappfood', '0003_auto_20200123_1232'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.ManyToManyField(to='snappfood.Address'),
        ),
    ]
