# Generated by Django 2.1.9 on 2020-01-23 22:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('snappfood', '0005_auto_20200123_2036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='address', to='snappfood.User'),
        ),
        migrations.AlterField(
            model_name='admin',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin', to='snappfood.Shop'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='items',
            field=models.ManyToManyField(related_name='cart', to='snappfood.Food'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cart', to='snappfood.User'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='snappfood.Invoice'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='users',
            field=models.ManyToManyField(related_name='discount', to='snappfood.User'),
        ),
        migrations.AlterField(
            model_name='food',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food', to='snappfood.Shop'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoice', to='snappfood.Address'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='discount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoice', to='snappfood.Discount'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='items',
            field=models.ManyToManyField(related_name='invoice', to='snappfood.Food'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='address',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='shop', to='snappfood.Address'),
        ),
        migrations.AlterField(
            model_name='user',
            name='favorite',
            field=models.ManyToManyField(related_name='liker', to='snappfood.Food'),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to='snappfood.User'),
        ),
    ]
